# docker-compose -f docker-compose-test.yaml up --build

version: "2.4"
x-net: &net
  networks:
      - main
services:
  db:
    <<: *net
    image: datajoint/mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=simple 
  workflow_miniscope:
    <<: *net
    build:
      context: .
    #image: workflow_miniscope:v0.0.0
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - MINISCOPE_ROOT_DATA_DIR=/main/test_data
      - DATABASE_PREFIX=test_
    command:
      - bash
      - -c
      - |
        echo "------ INTEGRATION TESTS ------"
        pytest tests/test_pipeline_generation.py
        tail -f /dev/null
    volumes:
      - /Users/davidgodinez/Desktop/data/U24/Miniscope-DAQ-V4:/main/test_data
    depends_on:
      db:
        condition: service_healthy
networks:
  main: